---

- name: "Get tags already present in local cache registry : {{ image.name }}"
  changed_when:
    - registry_query is defined
    - registry_query.stdout != ""
  register: registry_query
  ignore_errors: true
  ansible.builtin.command:
    cmd: >-
      skopeo list-tags --tls-verify=false --no-creds 
      docker://{{ image.cache_registry_url | default(docker_default_cache_registry_url) }}/{{ image.name }}

- name: "List tags already present in local cache registry : {{ image.name }}"
  when:
    - registry_query is defined
    - registry_query.stdout_lines != ""
  ansible.builtin.debug:
    msg: "{{ registry_query.stdout_lines | list }}"
