---

- name: registry-cli create folder
  ansible.builtin.file:
    path: "{{ docker_registry_cli_path }}"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: registry-cli deploy
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "{{ docker_registry_cli_path }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - registry.py
    - requirements-build.txt

- name: registry-cli set permissions
  ansible.builtin.file:
    path: "{{ docker_registry_cli_path }}/registry.py"
    owner: root
    group: root
    mode: "0755"

- name: registry-cli install python requirements
  ansible.builtin.pip:
    requirements: "{{ docker_registry_cli_path }}/requirements-build.txt"
