---

- name: Registry-cli create folder
  ansible.builtin.file:
    path: "{{ docker_registry_cli_path }}"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Registry-cli deploy
  with_items:
    - { file: registry.py, mode: "0755" }
    - { file: requirements-build.txt, mode: "0644" }
  ansible.builtin.copy:
    src: "files/{{ item.file }}"
    dest: "{{ docker_registry_cli_path }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"

- name: Registry-cli install python requirements
  loop: "{{ docker_registry_cli_pip_modules_list | flatten }}"
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
    # requirements: "{{ docker_registry_cli_path }}/requirements-build.txt"
  
