---

- name: registry-cli create folder
  ansible.builtin.file:
    path: "{{ docker_registry_cli_path }}"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: registry-cli deploy
  ansible.builtin.copy:
    src: "files/{{ item.file }}"
    dest: "{{ docker_registry_cli_path }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - { file: registry.py, mode: "0755" }
    - { file: requirements-build.txt, mode: "0644" }

- name: registry-cli install python requirements
  ansible.builtin.pip:
    requirements: "{{ docker_registry_cli_path }}/requirements-build.txt"
