---

- name: "Delete in local cache registry : {{ image.name }}:{{ tag }}"
  ansible.builtin.command:
    cmd: >-
      skopeo delete --tls-verify=false 
      docker://{{ image.cache_registry_url | default(docker_default_cache_registry_url) }}/{{ image.name }}:{{ tag | string }}
  register: resdel
  ignore_errors: true

# - ansible.builtin.debug:
#     var: resdel
