---

## {% if image.remote_registry_url is defined %}{{ image.remote_registry_url }}/{% endif %}
# {% if  docker_default_retag_keep_remote_registry_name  and  image.retag_keep_remote_registry_name %}
# {{ image.remote_registry_url | default(docker_default_remote_registry_url) }}/
# {% elif  not docker_default_retag_keep_remote_registry_name  and  image.retag_keep_remote_registry_name %}
# {{ image.remote_registry_url | default(docker_default_remote_registry_url) }}/
# {% endif %}

- name: "- {{ image.name }}:{{ tag | string }} - pull from external registry"
  community.docker.docker_image:
    name: "{{ image.remote_registry_url | default(docker_default_remote_registry_url) }}/{{ image.name }}:{{ tag | string }}"
    source: pull
  ignore_errors: true
  register: pull_result

- name: "- {{ image.name }}:{{ tag | string }} - retag and push in local cache registry"
  community.docker.docker_image:
    name: "{{ image.remote_registry_url | default(docker_default_remote_registry_url) }}/{{ image.name }}"
    repository: "{{ image.cache_registry_url | default(docker_default_cache_registry_url) }}/{{ image.name }}:{{ tag | string }}"
    tag: "{{ tag | string }}"
    push: "yes"
    source: local
  ignore_errors: true
  register: retag_result
  when: >
    pull_result.failed is defined
    and
    not pull_result.failed | bool

- name: "- {{ image.name }}:{{ tag | string }} - prune on local docker node"
  community.docker.docker_image:
    state: absent
    name: "{{ item }}"
    tag: "{{ tag | string }}"
  ignore_errors: true
  when: >
    retag_result.failed is defined
    and
    not retag_result.failed | bool
  with_items:
    - "{{ image.name }}"
    - "{{ image.remote_registry_url | default(docker_default_remote_registry_url) }}/{{ image.name }}"
    - "{{ image.cache_registry_url | default(docker_default_cache_registry_url) }}/{{ image.name }}"
