---
- name: Split image.name into namespace and image
  ansible.builtin.set_fact:
    dest_repo: ""

- name: Split image.name into namespace and image
  ansible.builtin.set_fact:
    dest_repo: "{{ image.name.split('/')[0] }}"
    # image: "{{ image.name.split('/')[1] }}"
  when: "'/' in image.name"


- name: "Sync to local registry : {{ image.name }}:{{ tag }}"
  ansible.builtin.command:
    cmd: >-
      skopeo sync 
      --src-tls-verify=false --dest-tls-verify=false 
      --src docker --dest docker 
      {{ image.remote_registry_url | default(docker_default_remote_registry_url) }}/{{ image.name }}:{{ tag | string }} 
      {{ image.cache_registry_url | default(docker_default_cache_registry_url) }}/{{ dest_repo }}
  register: resadd
  ignore_errors: true

- ansible.builtin.debug:
    var: resadd
