---
- name: install required python modules
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_python_module | flatten }}"
  # run_once: true

- name: login to hub.docker.com
  ansible.builtin.shell: docker login --username "{{ docker_hub_login }}" --password "{{ docker_hub_password }}"

- ansible.builtin.include_tasks:
    file: "tasks/sub-tasks/manage_image.yml"
  loop: "{{ docker_images_list | flatten }}"
  loop_control:
    loop_var: image
  when: docker_images_list is iterable
