---
- name: install required python modules
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_python_module | flatten }}"
  # run_once: true

# - name: login to hub.docker.com
#   ansible.builtin.shell:
#     cmd: docker login --username "{{ docker_hub_login }}" --password "{{ docker_hub_password }}"

- name: include tasks for image management
  ansible.builtin.include_tasks:
    file: "tasks/sub-tasks/manage_image.yml"
  loop: "{{ docker_images_list | flatten }}"
  loop_control:
    loop_var: image
    # label:
    #   - "{{ image.name }}:{{ image.tag }}"
    #   - "{{ image.state }}"
    extended: yes
  when: docker_images_list is iterable
